version: '3.3'
services:
    php:
        build:
            context: ./config/php.local
            dockerfile: .Dockerfile
        container_name: php
        volumes:
            - './app:/var/www/html'
        depends_on:
            - mariadb
        networks:
            - nginx_to_apache
            
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'
            - '/etc/letsencrypt/:/etc/letsencrypt/'
        networks:
            - nginx_to_apache 

    mariadb:
        image: mariadb:10.4
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - nginx_to_apache

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_bot
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        links:
            - mariadb
        ports:
            - 8082:80
        networks:
            - nginx_to_apache

    selenium:
       image: selenium/standalone-chrome
       extra_hosts:
             - "simple-docker-php-main-selenium-1:172.18.0.6"
       links:
           - php
       ports:
           - 4444:4444
       networks:
           - nginx_to_apache
           
networks:
    nginx_to_apache:
       external: true
